language: cpp
sudo: true

matrix:
  include:
    - os: linux
      compiler: g++
      before_install:
        - sudo apt-add-repository ppa:sonkun/sfml-development -y
        - sudo apt-get update -qq
      install:
        - sudo apt-get install libsfml-dev
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'boost-latest']
          packages: ['g++-5', 'libboost-dev']
      env: COMPILER=g++-5

    - os: linux
      compiler: g++
      before_install:
        - sudo apt-add-repository ppa:sonkun/sfml-development -y
        - sudo apt-get update -qq
      install:
        - sudo apt-get install libsfml-dev
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'boost-latest']
          packages: ['g++-6', 'libboost-dev']
      env: COMPILER=g++-6

    - os: linux
      compiler: clang
      before_install:
        - sudo apt-add-repository ppa:sonkun/sfml-development -y
        - sudo apt-get update -qq
      install:
        - sudo apt-get install libsfml-dev
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6', 'boost-latest']
          packages: ['clang-3.6', 'libboost-dev']
      env: COMPILER=clang-3.6

    - os: linux
      compiler: clang
      before_install:
        - sudo apt-add-repository ppa:sonkun/sfml-development -y
        - sudo apt-get update -qq
      install:
        - sudo apt-get install libsfml-dev
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7', 'boost-latest']
          packages: ['clang-3.7', 'libboost-dev']
      env: COMPILER=clang-3.7

script:
  - uname -a
  - $COMPILER --version
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER . && make -j
  - cd tests && make && make check
